name: project

dependencies:
  - python==3.7
  - pip
  - matplotlib
  - opencv
  - cudnn
  - cudatoolkit==10.1.243
  - sqlalchemy
  - psycopg2
  - flask
  - pandas
  - openpyxl
  - werkzeug
  - natsort
  - lmdb
  - nltk
  - numpy
  - scipy
  - six
  - keras
  - pip:
    - tensorflow-gpu==2.1.2
    - lxml
    - tqdm
    - seaborn
    - pillow
    - absl

